name: projek # Pastikan ini nama proyekmu
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Saya ubah sedikit ke 3.0.0 agar lebih aman (kompatibel banyak versi)

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # --- TAMBAHAN BARU (WAJIB ADA) ---
  intl: ^0.19.0           # Untuk format Rupiah & Tanggal
  image_picker: ^1.0.7    # Untuk upload foto bukti bayar
  pdf: ^3.10.4          # (Opsional) Jika nanti ingin fitur PDF
  printing: ^5.11.1     # (Opsional) Jika nanti ingin fitur Print
  # ---------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/